#pragma once
#ifndef TETGENR_VERSION_H
#define TETGENR_VERSION_H

#define TETGENR_VERSION          "@TETGENR_VERSION@"
#define TETGENR_INTERNAL_VERSION "@TETGENR_INTERNAL_VERSION@"
#define TETGENR_GIT_HASH         "@TETGENR_GIT_HASH@"
#define TETGENR_GIT_BRANCH       "@TETGENR_GIT_BRANCH@"
#define TETGENR_GIT_TAG          "@TETGENR_GIT_TAG@"
#define TETGENR_BUILD_TIME       "@TETGENR_BUILD_TIME@"
#define TETGENR_BUILD_TYPE       "@TETGENR_BUILD_TYPE@"

#endif
